// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWXscUPJ3jL3gCUuerFpFPfxx3c-1Xkkk',
    appId: '1:993892131921:web:a25be1d4941182408cc470',
    messagingSenderId: '993892131921',
    projectId: 'bagbliss-d9793',
    authDomain: 'bagbliss-d9793.firebaseapp.com',
    storageBucket: 'bagbliss-d9793.appspot.com',
    measurementId: 'G-961N0KHQS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0VjxWh-IqaYPIlF1QqTHW8rbc-UBXdLk',
    appId: '1:993892131921:android:01cf95f8b686f2408cc470',
    messagingSenderId: '993892131921',
    projectId: 'bagbliss-d9793',
    storageBucket: 'bagbliss-d9793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZGvbLDRPjfEO5ZmYBs25e9AgW9mptD0',
    appId: '1:993892131921:ios:cfb9895bb566c47a8cc470',
    messagingSenderId: '993892131921',
    projectId: 'bagbliss-d9793',
    storageBucket: 'bagbliss-d9793.appspot.com',
    iosClientId: '993892131921-kkndv1j2oqb1kb8e05kufb4upi9j3p4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bagBliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZGvbLDRPjfEO5ZmYBs25e9AgW9mptD0',
    appId: '1:993892131921:ios:daf22be9c8feec728cc470',
    messagingSenderId: '993892131921',
    projectId: 'bagbliss-d9793',
    storageBucket: 'bagbliss-d9793.appspot.com',
    iosClientId: '993892131921-aus36jfu526acsg2217eauocn3mrcaaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bagBliss.RunnerTests',
  );
}
